%% runRefineOnOldWorkspaces
% this script is used to take workspaces generated from UIA3
% and perform centroid detection and 
% generate 600x600 px centroid images which are then compiled per image
% and dimensionaly reduced using non-negative matrix factorization. 
% 1D slices of the centroid image features generated by NNMF are compiled
% and written as a .csv
parent_folder = strcat(uigetdir('Select an input folder'),'/');
infile =  dir(strcat(parent_folder,'*.mat'));
outputdir = strcat(uigetdir('Select an output folder'),'/');
filenames = {infile.name};
%%
for i = 1:length(filenames)
    lil_nam = extractBefore(filenames{i},"6");
    if strcmp("DEN",extractBefore(filenames{i},4))
        xchannel = 0;
    elseif strcmp(extract(filenames{i},1),extract(filenames{i},2))
        xchannel = 0;
    else
    xchannel = 1;
    end
    if xchannel == 0 % if we are not looking at an overlap channel
       load(strcat(parent_folder,filenames{i}),'img_array_red','img_array_green','mask_array','thresh','px') 
       if exist('thresh','var') == 0
            thresh = 0.245;
       end
       [XRed,hcRed] = UIA_NNMF(img_array_red,mask_array,thresh,px,px,6,2); 
       writematrix(XRed,strcat(outputdir,lil_nam,"_refinedX.csv")) 
       [XGreen,hcGrreen] = UIA_NNMF(img_array_green,mask_array,thresh,px,px,6,2); 
       writematrix(XGreen,strcat(outputdir,lil_nam,"_refinedX.csv")) 
       save(strcat(outputdir,lil_nam,'_refined_workspace'))
    else % if we are looking at an overlap image dataset
       load(strcat(parent_folder,filenames{i}),'img_overlap','mask_array','thresh','px')
        if exist('thresh','var') == 0
            thresh = 0.245;
       end
       [X,hc] = UIA_NNMF(img_overlap,mask_array,thresh,px,px,6,2);
       writematrix(X,strcat(outputdir,lil_nam,"_refinedX.csv"))
       save(strcat(outputdir,lil_nam,'_refined_workspace'))
    end
end
%%

